### PR TITLE
use v-app

### PR DESCRIPTION
**Pull request by BackgroundBoy**
use v-app in app.blade and override Vuetify theme. Please check whether the other Vue components are broken, on mine laptop it is all working correctly.

### CODE REVIEW

**Comment by CeylonT** [comment]
Unable to see a full notification message if the message is too long.

**Comment by CeylonT** [comment]
Otherwise, everything works fine.

**Comment by BackgroundBoy** [comment]
Dunno why when I switched to other branch then leave their files are still in my branch.  Otherwise scroll problem are fixed and there are major problem about cookie that i've encounter. Cookie are not user specific so I move to use cookie in laravel and implement everything again lol. Please check the cart feature(the so called god mode are gone!, **if u want to test then use the test area in cartItem.vue**)

**Comment by tirogen** [comment]
if it have any problems we will fix later

**Pull request merged**
