### PR TITLE
Automate new class

### PR DESCRIPTION
**Pull request by taan02991**
CourseClass table
Fields: id, date, time, hours, course_id
This will create all classes of the course after tutor create a course.
This will be used in the following features:
1. Calendar -> Fetch this table for the schedule of the course.
2. Class Postponement -> after successfully postponement you have to update the date and time of this table corresponding to postponement date.

### CODE REVIEW

**Comment by tongplw** [comment]
I think postponement is for individual classes not for courses but there are postpone button in every courses in my-courses page

**Comment by BackgroundBoy** [comment]
But aren't the course suppose to be postponable?

**Comment by taan02991** [comment]
> I think postponement is for individual classes not for courses but there are postpone buttons in every courses in my-courses page

So, you mean that postpone button should place on other page not on my-course page right?

**Comment by tongplw** [comment]
it should be placed in calendar maybe because users can choose whether which class they want to postpone

or you mean postponing the start date of the course only?

**Comment by taan02991** [comment]
Agree, I removed the button.

**Pull request merged**
