### PR TITLE
Request to be tutor

### PR DESCRIPTION
**Pull request by knotnuttanai**

### CODE REVIEW

**Comment by BackgroundBoy** [comment]
The pop-up confirm window have a non-unique element id (duplicate, when open in console the browser alert). Search page not consistency w/ student search(not serious though). Good job mate!

**Comment by BackgroundBoy** [comment]
Need to update with current 'dev' branch, also it is a good practice to not write appid and appkey into public file like .env.example in this case.

**Comment by knotnuttanai** [comment]
> Need to update with current 'dev' branch, also it is a good practice to not write appid and appkey into public file like .env.example in this case.



> The pop-up confirm window have a non-unique element id (duplicate, when open in console the browser alert). Search page not consistency w/ student search(not serious though). Good job mate!

All have been fixed.

**Comment by tongplw** [comment]
Let's merge it

**Pull request merged**
